version: '3'

services:
  silent-auction:
    image: docker.io/library/silent-auction:api
    environment:
      - SECRET_KEY=string
      - STRIPE_PUBLIC_KEY=pk_test_somevalue
      - STRIPE_PRIVATE_KEY=sk_test_somevalue
      - DOMAIN=http://localhost:5001
      - SERVER_TOKEN=testServerToken
      - IS_DEMO=true
    ports:
      - "5001:5000"
