"""add has paid boolean

Revision ID: 2bb0699f49a2
Revises: 9c9a2302202d
Create Date: 2024-01-14 22:06:53.506738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb0699f49a2'
down_revision = '9c9a2302202d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_paid', sa.Boolean(), nullable=False, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.drop_column('has_paid')

    # ### end Alembic commands ###
