"""update auction item datamodel

Revision ID: 36ec5861aaca
Revises: 42dfa70b9bc9
Create Date: 2024-01-09 21:20:25.788337

"""
from alembic import op
import sqlalchemy as sa
from silentauction.utils.date_utils import default_auction_end
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '36ec5861aaca'
down_revision = '42dfa70b9bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_bid', sa.Numeric(precision=10, scale=2), nullable=False, default=0))
        batch_op.add_column(sa.Column('bid_interval', sa.Numeric(precision=10, scale=2), nullable=False, default=0))
        batch_op.add_column(sa.Column('auction_start', sa.DateTime(), nullable=False, default=datetime.utcnow))
        batch_op.add_column(sa.Column('auction_end', sa.DateTime(), nullable=False, default=default_auction_end))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.drop_column('auction_end')
        batch_op.drop_column('auction_start')
        batch_op.drop_column('bid_interval')
        batch_op.drop_column('starting_bid')

    # ### end Alembic commands ###
