"""Add auction end

Revision ID: 53ee6ad0b8af
Revises: dab5101d78df
Create Date: 2024-01-09 17:55:00.201358

"""
from alembic import op
import sqlalchemy as sa
from silentauction.utils.date_utils import default_auction_end


# revision identifiers, used by Alembic.
revision = '53ee6ad0b8af'
down_revision = 'dab5101d78df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_end', sa.DateTime(), nullable=False, default=default_auction_end))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_column('auction_end')

    # ### end Alembic commands ###
