"""Update bid datamodel

Revision ID: 65c14c158e8f
Revises: ad93332518e2
Create Date: 2024-01-10 20:01:38.506870

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '65c14c158e8f'
down_revision = 'ad93332518e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, default=0))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, default=datetime.utcnow))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, default=datetime.utcnow))
        batch_op.add_column(sa.Column('auction_item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('bids_user_fk', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('bids_auction_items_fk', 'auction_items', ['auction_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_constraint('bids_user_fk', type_='foreignkey')
        batch_op.drop_constraint('bids_auction_items_fk', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('auction_item_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
