"""stripe product id

Revision ID: 9c9a2302202d
Revises: 65c14c158e8f
Create Date: 2024-01-14 20:38:55.965694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9a2302202d'
down_revision = '65c14c158e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
