"""update src to filename

Revision ID: ad93332518e2
Revises: d0c32c1b0241
Create Date: 2024-01-10 18:26:34.022391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad93332518e2'
down_revision = 'd0c32c1b0241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=75), nullable=False))
        batch_op.drop_column('src')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src', sa.VARCHAR(length=75), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
