"""Add auction item relationship

Revision ID: b72b28df978b
Revises: 8c05be8e147a
Create Date: 2024-01-09 02:15:48.301605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72b28df978b'
down_revision = '8c05be8e147a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('auction_id_fk', 'auctions', ['auction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_items', schema=None) as batch_op:
        batch_op.drop_constraint('auction_id_fk', type_='foreignkey')
        batch_op.drop_column('auction_id')

    # ### end Alembic commands ###
